[tool.poetry]
name = "deezer-downloader"
version = "0.1.0"
description = ""
authors = ["kmille <github@androidloves.me>"]
readme = "README.md"
packages = [{include = "deezer_downloader"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
flask = "^2.2.2"
python-mpd2 = "^3.0.5"
yt-dlp = "^2022.11.11"
pycryptodome = "^3.16.0"
jinja2 = "^3.1.2"
gunicorn = "^20.1.0"
flask-autoindex = "^0.6.6"
giphypop = "^0.3"


[tool.poetry.group.dev.dependencies]
pdbpp = "^0.10.3"
pytest = "^7.2.0"
python-magic = "^0.4.27"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
